config/routes.rb
Rails.application.routes.draw do
  resources :lists

  resources :records
  
  root 'app#main'
  get 'users/new'

  get 'typeChoose/:t' => 'app#typeChoose'
  post 'save_record' => 'app#save_record'

   post 'proc' => 'app#check'

   resources :users

end

app/models/list.rb
class List < ActiveRecord::Base

belongs_to :user
has_many :records

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    list = List.find_by(id: params[:id])
    @records = list.records
    p '11111111111111111111111111111111111111111111111111111111'
    p list

    @records.each do |r|
      data = {}
      r.fields.each do |f|
        data[f.name] = f.value
      end
      app_controller = AppController.new
      app_controller.check
    end
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    p params
    @user.lists.create(name: params[:name])
    redirect_to lists_path
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1 id='main_title'>Сервис библиографических описаний</h1>
<div id='main'>
<h3>Списки</h3>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
</div>

app/views/lists/new.html.erb
<h1 id='main_title'>Сервис библиографических описаний</h1>
<div id='main'>
<h3>Создание нового списка</h3>
<%= form_tag '/lists', method: :post do %>
  <p>
    <%= label_tag :"Название списка" %><br>
    <%= text_field_tag :name %>
  </p>

  <p>
    <%= submit_tag %>
  </p>
<% end %>


<%= link_to 'Назад', lists_path %>
</div>

app/views/lists/show.html.erb
<h1 id='main_title'>Сервис библиографических описаний</h1>
<div id='main'>
<p id="notice"><%= notice %></p>
<h3>Список записей</h3>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td></td>
        <td></td>
        <td></td>
      </tr>

  </tbody>
</table>

<br>
</div>