config/routes.rb
Rails.application.routes.draw do
  resources :lists

  resources :records
  
  root 'app#main'
  get 'users/new'

  get 'typeChoose/:t' => 'app#typeChoose'
  post 'save_record' => 'app#save_record'

   post 'proc' => 'app#check'

   resources :users

end

app/models/record.rb
class Record < ActiveRecord::Base

belongs_to :list
has_many :fields

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    # @record = Record.new(record_params)
    puts params

  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.fetch(:record, {})
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<h1 id='main_title'>Сервис создания библиографической ссылки для списка литературы</h1>
<div id='main'>

<%= form_tag('/proc', method: :post) do %><br>
  <div id="fio" class="form-group">
    <%= label_tag 'author[]', "ФИО" %>
    <%= text_field_tag 'author[]', nil, class: 'form-control' %>
    <!-- <a style="color:green;" onclick="return addField()" href="#">[+]</a> -->
    <button id="addField" type="button" class="btn btn-info">+</button>
  </div>


  <!-- <div type="button" class="btn-primary">
  <%= button_to "+", @article, remote: true %>
  </div> -->

  <div class="form-group">
    <%= label_tag 'title', "Заголовок:" %>
    <%= text_field_tag 'title', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'title_info', "Сведения, относящиеся к заглавию:" %>
    <%= text_field_tag 'title_info', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'editor', "Редактор:" %>
    <%= text_field_tag 'editor', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'compiler', "Составитель:" %>
    <%= text_field_tag 'compiler', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'organizations', "Наименование учреждения:" %>
    <%= text_field_tag 'organizations', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'year', "Год издания:" %>
    <%= text_field_tag 'year', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'publisher', "Издательство:" %>
    <%= text_field_tag 'publisher', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'volume', "Количество страниц:" %>
    <%= text_field_tag 'volume', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'volume_tome', "Количество томов:" %>
    <%= text_field_tag 'volume_tome', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'city', "Место издания (город):" %>
    <%= text_field_tag 'city', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'edition_number', "Номер издания:" %>
    <%= text_field_tag 'edition_number', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'number', "Номер выпуска:" %>
    <%= text_field_tag 'number', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'position', "Место размещения статьи (страницы):" %>
    <%= text_field_tag 'position', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'article_title', "Название статьи:" %>
    <%= text_field_tag 'article_title', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'url', "Интернет-ресурс:" %>
    <%= text_field_tag 'url', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'release_date', "Дата выпуска:" %>
    <%= text_field_tag 'release_date', nil, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    <%= label_tag 'accessing_resource', "Дата обращения:" %>
    <%= text_field_tag 'accessing_resource', nil, class: 'form-control' %><br>
  </div>
    <%= submit_tag 'Save' %>
<% end %>
</div>


<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>